### PR TITLE
Add missing smtp-id field

### LINKED ISSUE #247: Missing SmtpId field from GroupResubscribeEvent, UnsubscribeEvent, SpamReportEvent, GroupUnsubscribeEvent
@Jericho According to the SendGrid document regarding the Event Webhook handler except `OpenEvent` and `CloseEvent` rest has the `smtp-id` present.

I was working on a implementation for SendGrid, I thought I could use the StrongGrid (As most of the code will be similar) but there are some differences in implementations. I also see we can remove some code from the library too as we have build in helpers.

### PR DESCRIPTION
**Pull request by KoditkarVedant**
Fix #247 

- [x] Add smtp-id field in Add missing smtp-id field to groupresubscribe, unsubscribe, spamreport and groupunsubscribe events
- [x] Updated the test cases for each

### CODE REVIEW

**Comment by KoditkarVedant** [comment]
@Jericho when I checked there was no `X` for open and closed specifically in that chart. I'll move the property to `Event.cs` now.

**Comment by Jericho** [comment]
I see what you mean. There’s obvious discrepancies between the chart I found and the one you found!

**Comment by KoditkarVedant** [comment]
For my implementation I'm using this [chart](https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html#-Event-objects) as it was given as the reference for implementing the event webhook parser. Until we get the final verdict from sendgrid.

**Comment by HaydnDias** [comment]
Is there any update on this? Trying to use the webhook currently to be able to record smtp-id's, and noticed the property missing.

**Comment by Jericho** [comment]
Unfortunately there is no update. We can’t get anybody at SendGrid to help us understand the discrepancies in their documentation. I [opened an issue in their repo last October](
https://github.com/sendgrid/sendgrid-csharp/issues/792) and never heard back.

**Comment by KoditkarVedant** [comment]
@Jericho I visited the [event webhook](https://sendgrid.com/docs/for-developers/tracking-events/event/#events) docs through the link provided on [sendgrid](https://sendgrid.com) website. I think we should use the chart given [here](https://sendgrid.com/docs/for-developers/tracking-events/event/#event-objects) or we can verify with the json response provided for all events [here](https://sendgrid.com/docs/for-developers/tracking-events/event/#events).

what are your thoughts.

**Comment by HaydnDias** [comment]
Is this also related to #https://github.com/sendgrid/docs/issues/4865

**Comment by Jericho** [comment]
Yes it does seem related.

**Comment by Jericho** [comment]
I just released version 0.66.0 with revised model classes based on the recently updated SendGrid documentation. I suspect this will not be the last update I publish since I already found inconsistencies in their documentation. I raised issues in the documentation repository and will update StrongGrid is necessary. 

In the mean time, I am closing this PR since it is superseded by version 0.66.0 but thank you for collaborating and submitting this PR.

**Pull request closed without merging**
